"""Add unique constraints on MenuCategory.name and Campaign.name

Revision ID: d51652bf8f5b
Revises: b0555527ec0e
Create Date: 2022-02-01 23:57:56.846550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51652bf8f5b'
down_revision = 'b0555527ec0e'
branch_labels = None
depends_on = None


def upgrade():
    # BatchOp is required for sqlite
    with op.batch_alter_table('campaigns') as batch_op:
        batch_op.create_unique_constraint('uq_campaigns_name', ['name'])
    with op.batch_alter_table('menu_categories') as batch_op:
        batch_op.create_unique_constraint('uq_menu_categories_name', ['name'])
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'campaigns', ['name'])
    # op.create_unique_constraint(None, 'menu_categories', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # BatchOp is required for sqlite
    with op.batch_alter_table('menu_categories') as batch_op:
        batch_op.drop_constraint('uq_menu_categories', type_='unique')
    with op.batch_alter_table('campaigns') as batch_op:
        batch_op.drop_constraint('uq_campaigns_name', type_='unique')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'menu_categories', type_='unique')
    # op.drop_constraint(None, 'campaigns', type_='unique')
    # ### end Alembic commands ###
